language: java

matrix:
    include:
        - os: linux
          jdk: openjdk11
        - os: osx
          osx_image: xcode10.1

jdk: openjdk11

script:
    - ./gradlew build

after_success:
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then git fetch --unshallow; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./gradlew jacocoTestReport; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./gradlew sonarqube -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=$SONAR_KEY -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.login=$SONAR_TOKEN; fi
